# Analysis of Complex Networks 
## Assignment 1 (Group 6)
### Student: André Dussing  ID: 018113442F 

Github: https://github.com/andreunilux/Complex-Networks

In [29]:
# import necessary libraries
import networkx as nx
import numpy as np
import pandas as pd
import os

At first we set the path according to our dataset we are using (here Group6)


1. Facebook-Ego 
2. Twitter-Ego

In [30]:
path = "exercise_complex_network/Datasets/Group6"
path_facebook = os.path.join(path,"Facebook-Ego", "1684.edges" ) # 1. Facebook-Ego
path_twitter =  os.path.join(path,"Twitter-Ego", "2029971.edges" ) # 2. Twitter-Ego
# Now we read the edge list from the file and create the graph with NetworkX


facebook_graph = nx.read_edgelist(path_facebook, nodetype=int) # Undirected
twitter_graph = nx.read_edgelist(path_twitter, nodetype=int, create_using=nx.DiGraph()) #Directed




### (a) How many nodes and edges are there in the networks?

1. Facebook (Undirected)

In [31]:
facebook_nodes = facebook_graph.number_of_nodes()
facebook_edges = facebook_graph.number_of_edges()
print(f"Number of nodes: {facebook_nodes}")
print(f"Number of edges: {facebook_edges}")

Number of nodes: 157
Number of edges: 569


2. Twitter (Directed)

In [32]:
twitter_nodes = twitter_graph.number_of_nodes()
twitter_edges = twitter_graph.number_of_edges()
print(f"Number of nodes: {twitter_nodes}")
print(f"Number of edges: {twitter_edges}")

Number of nodes: 143
Number of edges: 2830


### (b) What are the maximum degree and the average degree of the networks?

1. Facebook (Undirected)

In [33]:
degrees = dict(facebook_graph.degree())
facebook_max_degree = max(degrees.values()) # maximum degree
facebook_average_degree = sum(degrees.values()) / facebook_nodes # average degree
print(f"Maxi Degree: {facebook_max_degree}")
print(f"Average Degree: {facebook_average_degree}")

Maxi Degree: 30
Average Degree: 7.248407643312102


2. Twitter (Directed)

In [34]:
# In-degree (number of incoming edges to a node)
in_degrees = dict(twitter_graph.in_degree())
twitter_max_in_degree = max(in_degrees.values())  # Maximum in-degree
twitter_average_in_degree = sum(in_degrees.values()) / twitter_nodes  # Average in-degree

# Out-degree (number of outgoing edges from a node)
out_degrees = dict(twitter_graph.out_degree())
twitter_max_out_degree = max(out_degrees.values())  # Maximum out-degree
twitter_average_out_degree = sum(out_degrees.values()) / twitter_nodes  # Average out-degree

print(f"Twitter-Ego Max In-Degree: {twitter_max_in_degree}")
print(f"Twitter-Ego Average In-Degree: {twitter_average_in_degree}")

print(f"Twitter-Ego Max Out-Degree: {twitter_max_out_degree}")
print(f"Twitter-Ego Average Out-Degree: {twitter_average_out_degree}")

Twitter-Ego Max In-Degree: 77
Twitter-Ego Average In-Degree: 19.79020979020979
Twitter-Ego Max Out-Degree: 81
Twitter-Ego Average Out-Degree: 19.79020979020979


### (c) Extract 5 - 8 nodes from the network and state them as a partial network. What is the adjacency matrix of the partial network? Why do we need adjacency matrix to describe the structure of the network?

In [35]:
# calculate adjacency matrix
def partial_network_adjacency(graph, nodes_to_extract):
    partial_graph = graph.subgraph(nodes_to_extract)
    adjacency_matrix = nx.adjacency_matrix(partial_graph)
    return adjacency_matrix

1. Facebook (Undirected)

In [43]:
facebook_sample_nodes = list(facebook_graph.nodes())[:6]  
facebook_adj_matrix= partial_network_adjacency(facebook_graph, facebook_sample_nodes)
print(f"Sample Nodes: {facebook_sample_nodes}")
print(f"Adjacency Matrix: {facebook_adj_matrix.todense()}")

Sample Nodes: [2793, 2787, 2773, 2666, 2679, 2756]
Adjacency Matrix: [[0 0 1 0 0 0]
 [0 0 0 0 1 1]
 [1 0 0 0 0 0]
 [0 0 0 0 1 0]
 [0 1 0 1 0 1]
 [0 1 0 0 1 0]]


2. Twitter (Directed)

In [45]:
twitter_sample_nodes = list(twitter_graph.nodes())[:6]
twitter_adj_matrix = partial_network_adjacency(twitter_graph, twitter_sample_nodes)
print(f"Sample Nodes: {twitter_sample_nodes}")
print(f"Adjacency Matrix: {twitter_adj_matrix.todense()}")

Sample Nodes: [17030398, 14263368, 19837036, 15077314, 23070306, 18354504]
Adjacency Matrix: [[0 1 1 1 1 0]
 [0 0 1 0 0 0]
 [1 1 0 1 1 1]
 [1 0 1 0 1 0]
 [1 1 1 1 0 0]
 [0 0 1 0 0 0]]


The adjacency matrix is a very practical and compact way to describe the structure of a network. The rows and columns of the matrix represent nodes, and the entries indicate whether there is an edge between a pair of nodes. For undirected graphs, the adjacency matrix is symmetric, while for directed graphs, it can be asymmetric.